version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - blognet
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass myblog
    volumes:
      - redisdata:/usr/share/redis/data
    ports:
      - '6379:6379'
    networks:
      - blognet
  db:
    image: mariadb:latest
    container_name: myblog-db
    environment:
      MYSQL_ROOT_PASSWORD: yoda
      MYSQL_DATABASE: myblog
      MYSQL_USER: user
      MYSQL_PASSWORD: yoda
    volumes:
      - dbdata:/usr/share/mariadb/data
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - blognet
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - blognet
    depends_on:
      - db
      - redis
      - elasticsearch
volumes:
  esdata:
    driver: local
  redisdata:
  dbdata:
networks:
  blognet:
