version: '3.3'

services:
  elasticsearch:
    container_name: myblog-es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    volumes:
      - esdata:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - blognet
  redis:
    container_name: myblog-redis
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass myblog
    volumes:
      - redisdata:/var/lib/redis/data
    ports:
      - '6379:6379'
    networks:
      - blognet
  dbserver:
    image: mariadb:latest
    container_name: myblog-db
    restart: always
    healthcheck:
      test:  "/usr/bin/mysql --user=user --password=yoda --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: yoda
      MYSQL_DATABASE: myblog
      MYSQL_USER: user
      MYSQL_PASSWORD: yoda
    volumes:
      - dbdata:/var/lib/mariadb/data
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - blognet
  web:
    container_name: myblog-web
    # command: ./boot.sh
    build: .
    ports:
      - "5000:5000"
    networks:
      - blognet
    # links:
    #   - dbserver
    #   - redis
    #   - elasticsearch
    # depends_on:
    #   - dbserver
  celery:
    container_name: myblog-celery
    build: .
    command: celery worker -A celery_worker.celery --loglevel=info
    links:
      - redis
    depends_on:
      - web
      - redis
volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
  dbdata:
    driver: local
networks:
  blognet:
