version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - blognet
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass myblog
    volumes:
      - redisdata:/usr/share/redis/data
    ports:
      - '6379:6379'
    networks:
      - blognet
volumes:
  esdata:
    driver: local
  redisdata:
networks:
  blognet:
