"""followers

Revision ID: 32993968dcf9
Revises: bb65d915ac22
Create Date: 2018-05-11 09:33:34.419097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32993968dcf9'
down_revision = 'bb65d915ac22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
