"""new fields in user model

Revision ID: bb65d915ac22
Revises: 018be0bcec4d
Create Date: 2018-05-10 15:38:34.260501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb65d915ac22'
down_revision = '018be0bcec4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_me', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_me')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
